#ifndef CLOCK_H
#define CLOCK_H

#define TIMER_INPUT_FREQ	(1193182)
#define TIMER_OUTPUT_FREQ	(100)
#define TIMER_DIVIDER		(TIMER_INPUT_FREQ / TIMER_OUTPUT_FREQ)
#define TIMER_DIVIDER_LOW	(TIMER_DIVIDER & 0xFF)
#define TIMER_DIVIDER_HIGH	((TIMER_DIVIDER >> 8) & 0xFF)

#endif
